version: "3.7"
services:
  news_cast_postgres:
    hostname: news_cast_postgres
    container_name: news_cast_postgres
    build:
      context: ./../docker-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=ncexplorer,eventuate
    ports:
      - "5432:5432"

  news_cast_kafka:
    hostname: news_cast_kafka
    container_name: news_cast_kafka
    build:
      context: ./../kafka/.
    ports:
      - "9092:9092"
      - "9093:9093"
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M
