version: "3.7"
services:
  news-cast-postgres:
    hostname: news-cast-postgres
    container_name: news-cast-postgres
    build:
      context: ./../docker-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=ncexplorer,eventuate
    ports:
      - "5432:5432"

  news-cast-kafka:
    hostname: news-cast-kafka
    container_name: news-cast-kafka
    build:
      context: ./../kafka/.
    ports:
      - "9092:9092"
      - "9093:9093"
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M
