image: maven:3.8.2-openjdk-17

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B clean install # -B batch mode makes Maven less verbose
          - mvn package coveralls:report -Dconsolerizer.show=false -DrepoToken=${COVERALLS_REPO_TOKEN}
          - bash <(curl -s https://codecov.io/bash)
          - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java $(find **/jacoco*.xml -printf '-r %p ')

  renovate:
    - step:
        caches:
          - maven
        script:
          - export RENOVATE_CONFIG=$(< renovate.json)
          - renovate