image: maven:3.8.5-openjdk-17

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn clean install
  custom:
      renovate:
        - step:
            image: renovate/renovate
            caches:
              - maven
            script:
              - export RENOVATE_CONFIG=$(< renovate.json)
              - renovate