version: "3.7"

networks:
  newscast:
    driver: bridge

services:
  news_cast_postgres:
    hostname: news_cast_postgres
    container_name: news_cast_postgres
    build:
      context: ./docker-files/docker-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=ncexplorer,eventuate
    ports:
      - "5432:5432"
    networks:
      - newscast

  news_cast_kafka:
    hostname: news_cast_kafka
    container_name: news_cast_kafka
    build:
      context: ./docker-files/kafka/.
    ports:
      - "9092:9092"
      - "9093:9093"
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M
    networks:
      - newscast

  news_cast_mock:
    hostname: news_cast_mock
    container_name: news_cast_mock
    build:
      context: news-cast-mock/.
    ports:
      - 8081:8081
    restart: on-failure
    networks:
      - newscast

  news_cast_cdc:
    hostname: news_cast_cdc
    container_name: news_cast_cdc
    build:
      context: news-cast-explorer-cdc/.
    ports:
      - "8085:8085"
    restart: on-failure
    networks:
      - newscast

  news_cast_fetcher:
    hostname: news_cast_fetcher
    container_name: news_cast_fetcher
    build:
      context: news-cast-explorer-fetcher/.
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - newscast

  news_cast_choreography:
    hostname: news_cast_choreography
    container_name: news_cast_choreography
    build:
      context: news-cast-explorer-saga-choreography/.
    ports:
      - 8083:8083
    restart: on-failure
    networks:
      - newscast
