services:
  news-cast-postgres:
    hostname: news-cast-postgres
    container_name: news-cast-postgres
    command: -c 'max_connections=400' -c 'shared_buffers=100MB'
    build:
      context: ./docker-files/docker-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=ncexplorer,eventuate

    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 0s

  news-cast-kafka:
    hostname: news-cast-kafka
    container_name: news-cast-kafka
    build:
      context: ./docker-files/kafka/.
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M

    depends_on:
      news-cast-postgres:
        condition: service_healthy

  news-cast-mock:
    hostname: news-cast-mock
    container_name: news-cast-mock
    build:
      context: news-cast-mock/.
    restart: on-failure

    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M
    depends_on:
      news-cast-postgres:
        condition: service_healthy

  news-cast-cdc:
    hostname: news-cast-cdc
    container_name: news-cast-cdc
    build:
      context: news-cast-explorer-cdc/.
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M

    depends_on:
      news-cast-postgres:
        condition: service_healthy

  news-cast-fetcher:
    hostname: news-cast-fetcher
    container_name: news-cast-fetcher
    build:
      context: news-cast-explorer-fetcher/.
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

    depends_on:
      news-cast-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--silent", "http:/127.0.0.1:8080/api/newscast/fetcher/actuator"]
      interval: 5s
      timeout: 240s
      retries: 60

  news-cast-choreography:
    hostname: news-cast-choreography
    container_name: news-cast-choreography
    build:
      context: news-cast-explorer-saga-choreography/.
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M

    depends_on:
      news-cast-postgres:
        condition: service_healthy

  news-cast-orchestration:
    hostname: news-cast-orchestration
    container_name: news-cast-orchestration
    build:
      context: news-cast-explorer-saga-orchestration/.
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M

    depends_on:
      news-cast-postgres:
        condition: service_healthy

  news-cast-fe:
    hostname: news-cast-fe
    container_name: news-cast-fe
    build:
      context: docker-files/nginx/.
    restart: on-failure
    expose:
      - 9000
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M

    depends_on:
      news-cast-fetcher:
        condition: service_healthy
