version: "3.7"
services:
  gui-builder:
    container_name: news-cast-fe-build
    build:
      context: ./docker-files/build-node/.
    volumes:
      - ./news-cast-explorer-fe/node_modules:/opt/news-cast-explorer-fe/node_modules
      - ./news-cast-explorer-fe/dist:/opt/news-cast-explorer-fe/dist
      - ./news-cast-explorer-fe:/opt/news-cast-explorer-fe
    user: "1000:1000"
    networks:
      - newscast
  cypress-builder:
    container_name: news-cast-cypress-build
    build:
      context: ./docker-files/build-node/.
    volumes:
      - ./e2e/node_modules:/opt/e2e/node_modules
      - ./e2e:/opt/e2e
    user: "1000:1000"
    networks:
      - newscast

  backend-builder:
    container_name: news-cast-be-build
    build:
      context: docker-files/build-maven/.
    volumes:
      - .:/opt/news-cast-explorer
      - ${HOME}/.m2:/root/.m2
    networks:
      - newscast

  backend-qa:
    container_name: news-cast-be-qa
    build:
      context: docker-files/qa-maven/.
    volumes:
      - .:/opt/news-cast-explorer
      - ${HOME}/.m2:/root/.m2
    networks:
      - newscast

  backend-report:
    container_name: news-cast-be-report
    build:
      context: docker-files/report-maven/.
    volumes:
      - .:/opt/news-cast-explorer
      - ${HOME}/.m2:/root/.m2
    networks:
      - newscast
