version: "3.7"
services:
  nc_postgres:
    hostname: nc_postgres
    container_name: nc_postgres
    build:
      context: ./docker-files/docker-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=ncexplorer,eventuate
    ports:
      - "5432:5432"

  nc_kafka:
    hostname: nc_kafka
    container_name: nc_kafka
    build:
      context: ./docker-files/kafka/.
    ports:
      - "9092:9092"
      - "9093:9093"
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 1000M
