services:
  news-cast-postgres:
    ports:
      - "5432:5432"

  news-cast-kafka:
    ports:
      - "9092:9092"
      - "9093:9093"
      - "2181:2181"

  news-cast-mock:
    ports:
      - "8081:8081"

  news-cast-cdc:
    ports:
      - "8085:8085"

  news-cast-fetcher:
    ports:
      - "8080:8080"

  news-cast-choreography:
    ports:
      - "8083:8083"

  news-cast-orchestration:
    ports:
      - "8082:8082"

  news-cast-fe:
    ports:
      - "9000:9000"
