image: cimg/openjdk:18.0.2

pipelines:
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step:
          caches:
            - maven
          script:
            - mvn clean install

  custom:
    renovate:
      - step:
          image: renovate/renovate
          caches:
            - maven
          script:
            - export RENOVATE_CONFIG=$(< renovate.json)
            - renovate
    master:
      - step:
          caches:
            - maven
          script:
            - mvn clean install
