version: 2
jobs:
  build-maven:
    machine:
      image: ubuntu-2004:202010-01


    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build and Test Maven
          command: make backend-build

  build-yarn:
    docker:
      - image: cimg/node:17.3.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: yarn install --force
          working_directory: news-cast-explorer-fe

      - run:
          command: yarn
          working_directory: news-cast-explorer-fe

  report-all:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Build and Test Node
          command: make build-node-docker

      - run:
          name: Build and Test Maven
          command: make report-maven-docker

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_all:
    jobs:
      - build-maven
      - build-yarn
      - report-all
