# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
         name: System prepare
         command: mvn -version

      - run:
         name: Build and Test
         command:  mvn clean install jacoco:prepare-agent package jacoco:report

      - run:
         name: Coverage Reports
         command: mvn omni-coveragereporter:report

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
