# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-maven:
    machine:
      image: ubuntu-2004:202010-01


    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install SDK 17
          command: wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz &&
            tar xvf openjdk-17.0.2_linux-x64_bin.tar.gz &&
            sudo mv jdk-17*/ /opt/jdk17 &&
            export JAVA_HOME=/opt/jdk17 &&
            export PATH=$PATH:$JAVA_HOME/bin

      - run:
          name: Maven Clean Install
          command: export JAVA_HOME=/opt/jdk17 &&
             export PATH=$PATH:$JAVA_HOME/bin &&
             mvn clean install

  build-yarn:
    docker:
      - image: cimg/node:18.10.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: yarn --force
          working_directory: news-cast-explorer-fe

      - run:
          command: yarn
          working_directory: news-cast-explorer-fe

  report-all:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install npm
      - run: npm update -g npm
      - run: sudo npm i -g yarn
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - run: nvm install 16.10.0
      - run: nvm use 16.10.0
      - run: nvm use 16.10.0 && node --version && cd news-cast-explorer-fe && yarn && yarn add jest && npm run coverage
      - run:
         name: System prepare
         command: mvn -version &&
            wget https://download.java.net/java/GA/jdk17.0.1/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-17.0.1_linux-x64_bin.tar.gz &&
            tar xvf openjdk-17.0.1_linux-x64_bin.tar.gz &&
            sudo mv jdk-17*/ /opt/jdk17 &&
            export JAVA_HOME=/opt/jdk17 &&
            export PATH=$PATH:$JAVA_HOME/bin &&
            mvn -version

      - run:
         name: Build and Test
         command:
             export JAVA_HOME=/opt/jdk17 &&
             export PATH=$PATH:$JAVA_HOME/bin &&
             mvn -version &&
             mvn clean install jacoco:prepare-agent package jacoco:report

      - run:
         name: Coverage Reports
         command:
              export JAVA_HOME=/opt/jdk17 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn -version &&
              mvn omni-coveragereporter:report

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_all:
    jobs:
      - build-maven
      - build-yarn
      - report-all
