name: news-cast-app-pull-request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Migrate Docker Compose
      run: make dc-migration

    - name: Build with Maven
      run:  mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Set up Node.js 22
      uses: actions/setup-node@v5
      with:
        node-version: '22'

    - name: Build Node JS and Test
      run: make build-node && npm i -g jest && make test-node
