name: news-cast-app

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test
      run:  mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Build Node JS and Test
    - run: make build-npm && npm i -g jest && make test-node

    - name: Coverage Reports
      run: mvn omni-coveragereporter:report
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
