name: news-cast-app-pull-request

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run:  mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build Node JS and Test
      run: make build-node && npm i -g jest && make test-node
